# Generated by Django 5.0 on 2024-02-13 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_task_assigned_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_by',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_to',
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='task_photos'),
        ),
    ]
